# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  db:
    image: postgres:latest
    user: postgres
    environment:
       POSTGRES_PASSWORD: example
       POSTGRES_DB: dev-db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dev-db"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - 5432
  app:
    image: nextjs-postgres
    build:
      context: .
    
    ports:
        - 3000:3000
    environment:
        DATABASE_URL: postgres://postgres:example@db:5432/dev-db?schema=public
        NODE_ENV: development
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    
  web:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:example@db:5432/dev-db?schema=public
    depends_on:
      - db
    command: 
       sh -c "npx prisma generate"
       sh -c " npm i @prisma/client@latest @prisma/adapter-pg"
       sh -c " npm run dev "
     
   
      
    